{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.12"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.1.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.1.3.jar",
          "url": "spring-boot-starter-validation-3.1.3.jar",
          "size": 4766,
          "sha512": "e6d79a25d8ce988e5309638342a92d27edbbad2ad65db27a6c8cff6f4af185b03ee611f3a64fa62cbda8dd8fc3bfead3fb16ef3264088c33a1ad48b72015ccfc",
          "sha256": "2bdeba5167bca4bf0d8cac6a8043298936ee665b936e6693c4a72a328749159c",
          "sha1": "fdf58f7fb49600f02dec49549bc629d2ae9c6de0",
          "md5": "0abda06e644e2c59ebdb734d6959393d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.12"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.1.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.1.3.jar",
          "url": "spring-boot-starter-validation-3.1.3.jar",
          "size": 4766,
          "sha512": "e6d79a25d8ce988e5309638342a92d27edbbad2ad65db27a6c8cff6f4af185b03ee611f3a64fa62cbda8dd8fc3bfead3fb16ef3264088c33a1ad48b72015ccfc",
          "sha256": "2bdeba5167bca4bf0d8cac6a8043298936ee665b936e6693c4a72a328749159c",
          "sha1": "fdf58f7fb49600f02dec49549bc629d2ae9c6de0",
          "md5": "0abda06e644e2c59ebdb734d6959393d"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.1.3.jar",
          "url": "spring-boot-starter-validation-3.1.3.jar",
          "size": 4766,
          "sha512": "e6d79a25d8ce988e5309638342a92d27edbbad2ad65db27a6c8cff6f4af185b03ee611f3a64fa62cbda8dd8fc3bfead3fb16ef3264088c33a1ad48b72015ccfc",
          "sha256": "2bdeba5167bca4bf0d8cac6a8043298936ee665b936e6693c4a72a328749159c",
          "sha1": "fdf58f7fb49600f02dec49549bc629d2ae9c6de0",
          "md5": "0abda06e644e2c59ebdb734d6959393d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-validation-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.1.3.jar",
          "url": "spring-boot-starter-validation-3.1.3.jar",
          "size": 4766,
          "sha512": "e6d79a25d8ce988e5309638342a92d27edbbad2ad65db27a6c8cff6f4af185b03ee611f3a64fa62cbda8dd8fc3bfead3fb16ef3264088c33a1ad48b72015ccfc",
          "sha256": "2bdeba5167bca4bf0d8cac6a8043298936ee665b936e6693c4a72a328749159c",
          "sha1": "fdf58f7fb49600f02dec49549bc629d2ae9c6de0",
          "md5": "0abda06e644e2c59ebdb734d6959393d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-validation-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.1.3-javadoc.jar",
          "url": "spring-boot-starter-validation-3.1.3-javadoc.jar",
          "size": 4745,
          "sha512": "3411b7ddcd8704f302ba1f13cccdb7b4f8d81e9eeb0587231d49ebcd2571c9ca57057ca36533b5b85dc37bc4871ee852de355b16aa9d43690b6bc5d1c83185ec",
          "sha256": "fe524f32abec465af084eaa18b8ac3e504fbbf1600c857462de1eb22f29bf132",
          "sha1": "68327949927909fd975233304d21d4c97e99b08f",
          "md5": "35877f9d7a2ee08d570c5a61020faab7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.1.3-sources.jar",
          "url": "spring-boot-starter-validation-3.1.3-sources.jar",
          "size": 4743,
          "sha512": "35fad05ce1a8ea07b628b4ce4025b11696cdfb7beb0c8d4291aba5344a0f3f3a62406eab380601e38c270c0d1436efcb7edcc6f4bd50b10531eb8cecefddfe92",
          "sha256": "432c84af73e3f731d6aae4591b52ec3578f31a9a89e88773033088a8de973681",
          "sha1": "536be13d63ce9a297233c56da5b6d7d163770a1c",
          "md5": "0b2d8e239ced1098ad60b294b403cd5f"
        }
      ]
    }
  ]
}
